# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/DDSS/DDSS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDSS || ORIG_REF_NAME==DDSS} -quiet] -quiet

# IP: bd/DDSS/ip/DDSS_mult_gen_0_0/DDSS_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDSS_mult_gen_0_0 || ORIG_REF_NAME==DDSS_mult_gen_0_0} -quiet] -quiet

# IP: bd/DDSS/ip/DDSS_dds_compiler_0_0/DDSS_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDSS_dds_compiler_0_0 || ORIG_REF_NAME==DDSS_dds_compiler_0_0} -quiet] -quiet

# IP: bd/DDSS/ip/DDSS_dds_compiler_1_0/DDSS_dds_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDSS_dds_compiler_1_0 || ORIG_REF_NAME==DDSS_dds_compiler_1_0} -quiet] -quiet

# XDC: bd/DDSS/DDSS_ooc.xdc
