set_property IOSTANDARD LVTTL [get_ports sys_clk_i]
set_property PACKAGE_PIN H4 [get_ports sys_clk_i]

set_property IOSTANDARD LVTTL [get_ports ext_rst_n]
set_property PACKAGE_PIN M2 [get_ports ext_rst_n]

set_property IOSTANDARD LVTTL [get_ports dac_sclk]
set_property PACKAGE_PIN M1 [get_ports dac_sclk]
set_property IOSTANDARD LVTTL [get_ports dac_sync_n]
set_property PACKAGE_PIN N1 [get_ports dac_sync_n]
set_property IOSTANDARD LVTTL [get_ports dac_data]
set_property PACKAGE_PIN L1 [get_ports dac_data]

set_property IOSTANDARD LVTTL [get_ports {switch[0]}]
set_property PACKAGE_PIN L2 [get_ports {switch[0]}]
set_property IOSTANDARD LVTTL [get_ports {switch[1]}]
set_property PACKAGE_PIN M2 [get_ports {switch[1]}]
set_property IOSTANDARD LVTTL [get_ports {switch[2]}]
set_property PACKAGE_PIN L3 [get_ports {switch[2]}]
set_property IOSTANDARD LVTTL [get_ports {switch[3]}]
set_property PACKAGE_PIN K3 [get_ports {switch[3]}]
